// Metro configuration.
//
// `withUniwindConfig` must be the OUTERMOST wrapper (uniwind docs, metro-config),
// so it wraps `expo/metro-config`'s default config and must stay last if another
// wrapper is ever added.
//
// `cssEntryFile` is the stylesheet the Metro transformer compiles with Tailwind,
// AND it has to be the same file the app imports. Both roles at once, because the
// `@import`/`@source` directives only take effect when Tailwind compiles the file,
// and Tailwind only compiles the file the BUNDLE brings in. Splitting them —
// browser-facing directives in a file nothing imports — produced an export with
// every token variable and not one utility class, which renders as a completely
// unstyled screen with an `Exported: dist` success message and no error anywhere.
// Measured 2026-09-29; the screenshot is what caught it, not the build.
//
// The `@source` globs are what make Tailwind scan `app/` and the rest of `src/`:
// Tailwind scans from the entry's own directory, so without them the routes and
// the primitives compile to nothing.
const { getDefaultConfig } = require("expo/metro-config");
const { withUniwindConfig } = require("uniwind/metro");

const config = getDefaultConfig(__dirname);

const uniwind = withUniwindConfig(config, {
	cssEntryFile: "./src/ui/theme.css",
	// Generated by the Metro run itself; committed, so `tsc --noEmit` works on a
	// fresh clone without starting the bundler first.
	dtsFile: "./src/uniwind-types.d.ts",
	// Pinned rather than inherited. Tailwind expresses every spacing step in
	// `rem`, and the design kit's geometry is a 4pt grid (`tokens.json §
	// space.base`) where `p-4` must be exactly 16px. The polyfill is what decides
	// that on native; leaving it to a default means a `min-h-11` touch target is
	// 44px on one platform and something else on another — invisible in the class
	// name, visible only as a mis-sized control in a screenshot.
	polyfills: { rem: 16 },
});

/*
 * Guard for an upstream packaging gap in uniwind 1.12.0.
 *
 * Uniwind replaces react-native-web's own component modules with its own web
 * shims: its metro resolver rewrites a resolution that lands on
 * `react-native-web/dist/exports/<Name>/index.js` into `uniwind/components/<Name>`
 * for every name in its SUPPORTED_COMPONENTS list. That list contains
 * `InputAccessoryView`, but the package ships only the NATIVE shim for it
 * (`src/components/native/InputAccessoryView.tsx`) and no web one, so
 * `exports["./components/*"]` resolves to
 * `dist/module/components/web/InputAccessoryView.js`, which does not exist.
 *
 * Metro then returns null for that request — and because react-native-web's own
 * `dist/index.js` re-exports `InputAccessoryView`, this single missing file
 * fails the WHOLE web bundle: `expo export --platform web` dies with
 * "Unable to resolve module ./exports/InputAccessoryView". Measured 2026-09-29
 * with uniwind 1.12.0 / expo 57.0.26 / react-native-web 0.21.3; a plain
 * `getDefaultConfig` bundle of the same tree exports cleanly, so uniwind's
 * redirect is the cause and not the tree.
 *
 * The guard restores Metro's own resolution when, and only when, uniwind
 * declines to resolve. For this component that is also the correct answer:
 * react-native-web renders it as its own `UnimplementedView`, which is exactly
 * what an unimplemented component should be. It warns rather than failing
 * silently, so the day uniwind ships the missing shim the warning is the signal
 * that this block can go — and if a future gap is NOT benign, the warning names
 * the module instead of hiding it.
 */
const uniwindResolveRequest = uniwind.resolver.resolveRequest;
uniwind.resolver.resolveRequest = (context, moduleName, platform) => {
	let resolved;
	try {
		resolved = uniwindResolveRequest(context, moduleName, platform);
	} catch (error) {
		// Uniwind's redirect throws here rather than returning null, so an
		// unguarded call takes the whole bundle down with it.
		console.warn(
			`[metro] uniwind threw resolving "${moduleName}" (${platform}): ` +
				`${error?.message ?? error}. ` +
				"Using Metro's own resolution — see the guard in metro.config.js",
		);
		return context.resolveRequest(context, moduleName, platform);
	}
	if (resolved != null) return resolved;
	console.warn(
		`[metro] uniwind declined to resolve "${moduleName}" (${platform}); ` +
			"using Metro's own resolution — see the guard in metro.config.js",
	);
	return context.resolveRequest(context, moduleName, platform);
};

module.exports = uniwind;
