// Metro configuration. This stays JavaScript: Metro and Expo load `metro.config.js`
// with require() before any TypeScript tooling exists, so it cannot be `.ts`.
//
// `withUniwindConfig` must be the OUTERMOST wrapper (uniwind docs, metro-config),
// so it wraps `expo/metro-config`'s default config and must stay last if another
// wrapper is ever added.
//
// `cssEntryFile` is the stylesheet the Metro transformer compiles with Tailwind,
// AND it has to be the same file the app imports. Both roles at once, because the
// `@import`/`@source` directives only take effect when Tailwind compiles the file,
// and Tailwind only compiles the file the BUNDLE brings in. Splitting them —
// browser-facing directives in a file nothing imports — produced an export with
// every token variable and not one utility class, which renders as a completely
// unstyled screen with an `Exported: dist` success message and no error anywhere.
// Measured 2026-09-29; the screenshot is what caught it, not the build.
//
// The `@source` globs are what make Tailwind scan `app/` and the rest of `src/`:
// Tailwind scans from the entry's own directory, so without them the routes and
// the primitives compile to nothing.
const { getDefaultConfig } = require("expo/metro-config");
const { withUniwindConfig } = require("uniwind/metro");

const config = getDefaultConfig(__dirname);

const uniwind = withUniwindConfig(config, {
	cssEntryFile: "./src/ui/theme.css",
	// Generated by the Metro run itself; committed, so `tsc --noEmit` works on a
	// fresh clone without starting the bundler first.
	dtsFile: "./src/uniwind-types.d.ts",
	// Pinned rather than inherited. Tailwind expresses every spacing step in
	// `rem`, and the design kit's geometry is a 4pt grid (`tokens.json §
	// space.base`) where `p-4` must be exactly 16px. The polyfill is what decides
	// that on native; leaving it to a default means a `min-h-11` touch target is
	// 44px on one platform and something else on another — invisible in the class
	// name, visible only as a mis-sized control in a screenshot.
	polyfills: { rem: 16 },
});

/*
 * Guard for an upstream packaging gap in uniwind 1.12.0, scoped to the ONE module
 * it affects.
 *
 * Uniwind replaces react-native-web's own component modules with its own web
 * shims: its metro resolver rewrites a resolution that lands on
 * `react-native-web/dist/exports/<Name>/index.js` into `uniwind/components/<Name>`
 * for every name in its SUPPORTED_COMPONENTS list. That list contains
 * `InputAccessoryView`, but the package ships only the NATIVE shim for it
 * (`src/components/native/InputAccessoryView.tsx`) and no web one, so
 * `exports["./components/*"]` points at
 * `dist/module/components/web/InputAccessoryView.js`, which does not exist.
 *
 * Metro then throws — the resolver THROWS rather than returning null, which is why
 * this needs a try/catch and not just a null check — and because react-native-web's
 * own `dist/index.js` re-exports `InputAccessoryView`, that single missing file
 * fails the WHOLE web bundle: `expo export --platform web` dies with
 * "Unable to resolve module ./exports/InputAccessoryView". Measured 2026-09-29 with
 * uniwind 1.12.0 / expo 57.0.26 / react-native-web 0.21.3.
 *
 * WHAT THIS DISABLES, exactly: for this one specifier the app gets
 * react-native-web's own module instead of a uniwind shim. `InputAccessoryView` is
 * a keyboard accessory bar, and react-native-web renders it as `UnimplementedView`
 * — renders nothing. There is no uniwind behaviour being lost behind it, because
 * uniwind ships no web implementation for it to lose. Nothing in `app/` or `src/`
 * imports the component; it is in the graph only because react-native-web's index
 * re-exports every component it has.
 *
 * WHY IT IS SCOPED RATHER THAN GENERAL: a blanket "fall back whenever uniwind
 * declines" would turn any FUTURE uniwind resolution failure into a silent
 * downgrade — a component the app does use would lose its class-name handling and
 * the web target would stop being a truthful preview of the app while still
 * reporting a successful export. Scoped this way, any other failure still fails
 * the build loudly, which is the behaviour a reviewer wants.
 */
const UNIWIND_MISSING_WEB_SHIM = "exports/InputAccessoryView";

/* The specifier alone is not enough: a suffix match would also swallow a
 * same-named `exports/InputAccessoryView` from an unrelated package. The gap
 * exists only where react-native-web's own index re-exports the component, so the
 * request must also come from inside react-native-web. */
const isKnownGap = (context, moduleName) =>
	moduleName.endsWith(UNIWIND_MISSING_WEB_SHIM) &&
	/[\\/]react-native-web[\\/]/.test(context.originModulePath ?? "");

const uniwindResolveRequest = uniwind.resolver.resolveRequest;
uniwind.resolver.resolveRequest = (context, moduleName, platform) => {
	try {
		return uniwindResolveRequest(context, moduleName, platform);
	} catch (error) {
		if (!isKnownGap(context, moduleName)) throw error;
		console.warn(
			`[metro] uniwind has no web shim for "${moduleName}" (${platform}); ` +
				"using react-native-web's own module — see metro.config.js. " +
				"This is the InputAccessoryView gap, not a new one.",
		);
		return context.resolveRequest(context, moduleName, platform);
	}
};

module.exports = uniwind;
