allowBuilds:
  esbuild: set this to true or false
minimumReleaseAgeExclude:
  - expo-constants@57.0.20
  - expo-modules-core@57.0.20
  - expo@57.0.26
  - '@expo/ui@57.0.21'
  - expo-router@57.0.24
  - lucide-react-native@1.49.0
