/* GENERATED by scripts/build-theme.mjs — do not edit by hand.
 *
 * The design kit's values as TypeScript, generated from
 * design/tokens/tokens.json. Pure data and pure functions only: this module
 * must stay importable from a Node test, so it never touches React Native.
 *
 * Reach for a className first. This exists for the three cases a class name
 * cannot express — a value handed to a non-React-Native API (an SVG icon's
 * colour prop, the status bar style), an arithmetic decision (a layout
 * breakpoint), and the tests that pin the token contract.
 */

/** The two themes the app resolves to. `system` is a preference, not a theme. */
export type ThemeName = "light" | "dark";

/** What the reader chose in settings. `system` follows the OS appearance. */
export type ThemePreference = "light" | "dark" | "system";

/** Every colour role, in the order the kit declares them. */
export const COLOR_ROLES = [
	"canvas",
	"surface",
	"elevated",
	"sunken",
	"message-surface",
	"row-hover",
	"row-selected",
	"ink",
	"ink-muted",
	"ink-dim",
	"ink-disabled",
	"hairline",
	"hairline-strong",
	"border-control",
	"accent",
	"accent-hover",
	"accent-active",
	"accent-wash",
	"accent-muted",
	"accent-border",
	"on-accent",
	"accent-alt",
	"accent-alt-wash",
	"success",
	"success-wash",
	"success-border",
	"warning",
	"warning-wash",
	"warning-border",
	"danger",
	"danger-wash",
	"danger-border",
	"info",
	"info-wash",
	"info-border",
	"diff-add",
	"diff-add-surface",
	"diff-remove",
	"diff-remove-surface",
	"diff-hunk",
	"diff-hunk-surface",
	"diff-context",
	"scrim",
	"shadow-color",
	"focus-ring-photo-inner",
	"focus-ring-photo-outer",
] as const;

export type ColorRole = (typeof COLOR_ROLES)[number];

/** Roles whose value is the same in both themes ({ value } in the tokens). */
export const THEME_INVARIANT_ROLES = [
	"scrim",
	"shadow-color",
	"focus-ring-photo-inner",
	"focus-ring-photo-outer",
] as const;

/**
 * The resolved palette per theme: every value is a lowercase hex or a
 * semantic string, taken verbatim from the tokens (no transform, no casing).
 */
export const PALETTE: Record<ThemeName, Record<ColorRole, string>> = {
	light: {
		"canvas": "#f2ede3",
		"surface": "#f7f5ee",
		"elevated": "#fefdfa",
		"sunken": "#ece6d8",
		"message-surface": "#fcfbf7",
		"row-hover": "#edece7",
		"row-selected": "#ebe7d8",
		"ink": "#211e18",
		"ink-muted": "#4e4940",
		"ink-dim": "#656056",
		"ink-disabled": "#9a9488",
		"hairline": "#dad5cb",
		"hairline-strong": "#c9c3b6",
		"border-control": "#857f70",
		"accent": "#137742",
		"accent-hover": "#116036",
		"accent-active": "#0c4b2a",
		"accent-wash": "#e7f1e8",
		"accent-muted": "#cfe5d4",
		"accent-border": "#47795b",
		"on-accent": "#f6faf8",
		"accent-alt": "#6c5f9a",
		"accent-alt-wash": "#f0edf8",
		"success": "#19764a",
		"success-wash": "#e6f1ea",
		"success-border": "#3e6b4e",
		"warning": "#8a5800",
		"warning-wash": "#f5ecd9",
		"warning-border": "#7a5a1e",
		"danger": "#b23a31",
		"danger-wash": "#f7e7e4",
		"danger-border": "#96544c",
		"info": "#2368a8",
		"info-wash": "#e9ebef",
		"info-border": "#486893",
		"diff-add": "#19764a",
		"diff-add-surface": "#e6f1ea",
		"diff-remove": "#b23a31",
		"diff-remove-surface": "#f7e7e4",
		"diff-hunk": "#2368a8",
		"diff-hunk-surface": "#e9ebef",
		"diff-context": "#656056",
		"scrim": "#0b0a08b3",
		"shadow-color": "#0b0a08",
		"focus-ring-photo-inner": "#fffefb",
		"focus-ring-photo-outer": "#14110c",
	},
	dark: {
		"canvas": "#22201c",
		"surface": "#2b2721",
		"elevated": "#322d22",
		"sunken": "#1d1b19",
		"message-surface": "#2e2a21",
		"row-hover": "#302d29",
		"row-selected": "#372f24",
		"ink": "#f1eee6",
		"ink-muted": "#c2bcaf",
		"ink-dim": "#a6a091",
		"ink-disabled": "#5f5a4e",
		"hairline": "#403b2c",
		"hairline-strong": "#4d4633",
		"border-control": "#837c6d",
		"accent": "#38c96a",
		"accent-hover": "#5ad584",
		"accent-active": "#2bb25c",
		"accent-wash": "#16281d",
		"accent-muted": "#1d3a28",
		"accent-border": "#4a8160",
		"on-accent": "#16130e",
		"accent-alt": "#b0a7f7",
		"accent-alt-wash": "#242233",
		"success": "#57c785",
		"success-wash": "#16281d",
		"success-border": "#4f8465",
		"warning": "#e0b04b",
		"warning-wash": "#2a2213",
		"warning-border": "#8c773c",
		"danger": "#ef8078",
		"danger-wash": "#2e1b18",
		"danger-border": "#ac675d",
		"info": "#86b3f2",
		"info-wash": "#192332",
		"info-border": "#5a7ba8",
		"diff-add": "#57c785",
		"diff-add-surface": "#23352a",
		"diff-remove": "#ef8078",
		"diff-remove-surface": "#432a26",
		"diff-hunk": "#86b3f2",
		"diff-hunk-surface": "#22303f",
		"diff-context": "#a6a091",
		"scrim": "#0b0a08b3",
		"shadow-color": "#0b0a08",
		"focus-ring-photo-inner": "#fffefb",
		"focus-ring-photo-outer": "#14110c",
	},
};

/** Type steps. size is pt/sp, lineHeight a unitless multiplier. */
export const TYPE_STEPS = {
	"display": { size: 28, lineHeight: 1.2, weight: 600, letterSpacing: -0.02, face: "sans" },
	"title": { size: 20, lineHeight: 1.3, weight: 600, letterSpacing: -0.012, face: "sans" },
	"heading": { size: 17, lineHeight: 1.35, weight: 600, letterSpacing: -0.006, face: "sans" },
	"body-lg": { size: 17, lineHeight: 1.5, weight: 400, letterSpacing: 0, face: "sans" },
	"body": { size: 16, lineHeight: 1.5, weight: 400, letterSpacing: 0, face: "sans" },
	"body-sm": { size: 14, lineHeight: 1.45, weight: 400, letterSpacing: 0, face: "sans" },
	"meta": { size: 12, lineHeight: 1.4, weight: 500, letterSpacing: 0, face: "sans" },
	"label": { size: 15, lineHeight: 1.2, weight: 600, letterSpacing: -0.005, face: "sans" },
	"mono": { size: 13, lineHeight: 1.5, weight: 400, letterSpacing: 0, face: "mono" },
	"mono-sm": { size: 12, lineHeight: 1.45, weight: 400, letterSpacing: 0, face: "mono" },
	"mono-code": { size: 13, lineHeight: 1.6, weight: 400, letterSpacing: 0, face: "mono" },
	"mono-label": { size: 11, lineHeight: 1.2, weight: 600, letterSpacing: 0.06, face: "mono" },
} as const;

export type TypeStepName = keyof typeof TYPE_STEPS;

/** Corner radii, in pt. Assigned by what the object is, never by taste. */
export const RADII = {
	"xs": 2,
	"sm": 6,
	"md": 10,
	"lg": 14,
	"frame": 16,
	"full": 9999,
} as const;

/** The heights a control may declare. */
export const CONTROL_HEIGHTS = {
	"sm": { height: 32, paddingX: 12, minTouch: 44, icon: 14, gap: 6, type: "meta" },
	"md": { height: 44, paddingX: 16, minTouch: 44, icon: 16, gap: 8, type: "label" },
	"lg": { height: 50, paddingX: 24, minTouch: 50, icon: 18, gap: 10, type: "label" },
	"icon": { height: 44, width: 44, icon: 20 },
	"fab": { height: 56, width: 56, icon: 24 },
} as const;

export const TOUCH_TARGET = {
	ios: 44,
	android: 48,
	/** The floor every interactive control here meets, on both platforms. */
	minimum: 44,
	/** A visually smaller control may stay small only if its hit area is padded
	 * out to `minimum` (slop). Hit areas may never overlap. */
	minimumVisualWithSlop: 32,
} as const;

export const LIST_GEOMETRY = {
	rowMinHeight: 56,
	rowTwoLineHeight: 64,
	rowPaddingX: 16,
	rowPaddingY: 10,
	separatorInset: 16,
} as const;

export const DURATIONS = {
	"instant": 80,
	"fast": 120,
	"base": 180,
	"slow": 240,
	"reveal": 320,
	"draw": 480,
	"close": 400,
	"beat": 700,
} as const;

export const EASINGS = {
	"out-quart": "cubic-bezier(0.25, 1, 0.5, 1)",
	"out-expo": "cubic-bezier(0.16, 1, 0.3, 1)",
	"in-out": "cubic-bezier(0.65, 0, 0.35, 1)",
	"linear": "linear",
} as const;

/** The two shadows in the system. In-flow content is never lifted by one:
 * elevation there is a background step (canvas -> surface -> elevated). These
 * belong to objects that leave the flow, and both platforms must be set or one
 * of them gets nothing.
 */
export const ELEVATIONS = {
	"overlay": { light: "0 12px 32px -12px rgb(20 17 12 / 0.25)", dark: "0 12px 32px -12px rgb(0 0 0 / 0.6)", androidElevation: 8 },
	"frame": { light: "0 1px 2px rgb(20 17 12 / 0.06), 0 24px 48px -24px rgb(20 17 12 / 0.28)", dark: "0 1px 2px rgb(0 0 0 / 0.4), 0 24px 48px -24px rgb(0 0 0 / 0.55)", androidElevation: 2 },
} as const;

/** The stacking ladder, named. A seventh level is a sign something is
 * stacked that should be a route.
 */
export const Z_LEVELS = {
	"base": 0,
	"sticky": 10,
	"composer": 20,
	"pendingCard": 30,
	"sheet": 40,
	"dialog": 50,
	"toast": 60,
} as const;

/** The global duration cap under reduced motion. A cap, not zero: an
 * instantaneous colour change loses the affordance that a press IS feedback. */
export const REDUCED_MOTION_DURATION_CAP_MS = 120;
/** Screen metrics. A literal that appears twice drifts; these do not. */
export const LAYOUT = {
	gutter: 16,
	gutterLarge: 20,
	gutterTablet: 24,
	headerHeight: 56,
	composerMinHeight: 56,
	contentMaxWidthTablet: 560,
	contentMaxWidthTabletLandscape: 640,
	contentMaxWidthLandscapePhone: 620,
	/** Above this width the list and the detail sit side by side, and the
	 * layout must collapse to one column at half of it. */
	tabletBreakpoint: 700,
} as const;

/** The CSS custom property a role resolves through. */
export const cssColorVar = (role: ColorRole): string => "--color-" + role;

/** Resolve a role in a concrete theme, without going through CSS. */
export const resolveColor = (role: ColorRole, theme: ThemeName): string =>
	PALETTE[theme][role];

/**
 * Turn the reader's preference into the theme that actually renders.
 *
 * `system` is not a third theme — it is the absence of an override, and the
 * OS appearance supplies the answer. Keeping that resolution a pure function
 * of two values is what makes it testable in Node, where neither React
 * Native nor the OS is present.
 */
export const resolveTheme = (
	preference: ThemePreference,
	systemScheme: ThemeName | null | undefined,
): ThemeName => {
	if (preference === "light" || preference === "dark") return preference;
	return systemScheme === "dark" ? "dark" : "light";
};
