import Svg, { Circle, Path } from "react-native-svg";

/**
 * The brand mark, stroke-only so it inherits the ink of whatever surface it lands
 * on — one asset for both themes (design/app-icon/mark.svg).
 *
 * The geometry is COPIED from that file, which is generated by
 * `design/app-icon/build-icons.mjs`. A copy can drift, so it is worth being
 * explicit about why it is one: the only dependency-free way to draw an SVG in
 * React Native is to build it from primitives, and `react-native-svg-transformer`
 * is not in the shared dependency set. If the mark changes, this is the second
 * place to change, and the fix that removes the copy is a transformer pass or a
 * geometry token.
 *
 * PRIVATE TO `empty-state.tsx` UNTIL the composer home needed it at 32 pt
 * (`ink-muted`; the empty state draws it at 48 `ink-dim`). It is exported from
 * its own module now so no caller copies the geometry a second time — two
 * drawings of one mark would drift the moment the asset changes.
 */
export const BrandMark = ({ size, color }: { size: number; color: string }) => (
	<Svg
		width={size}
		height={size}
		viewBox="285 253 520 520"
		fill="none"
		// Decorative where it is drawn: the text around it carries the meaning, and
		// a screen reader announcing "image" before it would be noise.
		accessibilityElementsHidden
		// `aria-hidden` is what hides it on the WEB build: react-native-web copies
		// `importantForAccessibility` onto the <svg> verbatim as an attribute no
		// assistive technology reads, so the decorative mark was announced as an
		// unnamed graphic on every empty state. The two native props stay for
		// device screen readers.
		aria-hidden
		importantForAccessibility="no"
	>
		<Circle cx={490} cy={355} r={78} stroke={color} strokeWidth={35} />
		<Circle cx={720} cy={326} r={42} stroke={color} strokeWidth={29} />
		<Circle cx={368} cy={686} r={41} stroke={color} strokeWidth={29} />
		<Path
			d="M370 645 V545 a90 90 0 0 1 90 -90 h60 a78 78 0 0 1 66 44"
			stroke={color}
			strokeWidth={33}
			strokeLinecap="round"
			fill="none"
		/>
		<Path
			d="M590 498 V750"
			stroke={color}
			strokeWidth={33}
			strokeLinecap="round"
		/>
		<Path
			d="M600 492 C 646 512 686 480 706 400 L 712 378"
			stroke={color}
			strokeWidth={33}
			strokeLinecap="round"
			fill="none"
		/>
	</Svg>
);
