import { Text, View } from "react-native";
import Svg, { Circle, Path } from "react-native-svg";

import { useTokenColor } from "@/ui/appearance";
import { Button } from "@/ui/components/button";
import { emptyStateClasses } from "@/ui/variants";

/**
 * The brand mark, stroke-only so it inherits the ink of whatever surface it lands
 * on — one asset for both themes (design/app-icon/mark.svg).
 *
 * The geometry is COPIED from that file, which is generated by
 * `design/app-icon/build-icons.mjs`. A copy can drift, so it is worth being
 * explicit about why it is one: the only dependency-free way to draw an SVG in
 * React Native is to build it from primitives, and `react-native-svg-transformer`
 * is not in the shared dependency set. If the mark changes, this is the second
 * place to change, and the fix that removes the copy is a transformer pass or a
 * geometry token.
 */
const BrandMark = ({ size, color }: { size: number; color: string }) => (
	<Svg
		width={size}
		height={size}
		viewBox="285 253 520 520"
		fill="none"
		// Decorative here: the headline below carries the meaning, and a screen
		// reader announcing "image" before it would be noise.
		accessibilityElementsHidden
		// `aria-hidden` is what hides it on the WEB build: react-native-web copies
		// `importantForAccessibility` onto the <svg> verbatim as an attribute no
		// assistive technology reads, so the decorative mark was announced as an
		// unnamed graphic on every empty state. The two native props stay for
		// device screen readers.
		aria-hidden
		importantForAccessibility="no"
	>
		<Circle cx={490} cy={355} r={78} stroke={color} strokeWidth={35} />
		<Circle cx={720} cy={326} r={42} stroke={color} strokeWidth={29} />
		<Circle cx={368} cy={686} r={41} stroke={color} strokeWidth={29} />
		<Path
			d="M370 645 V545 a90 90 0 0 1 90 -90 h60 a78 78 0 0 1 66 44"
			stroke={color}
			strokeWidth={33}
			strokeLinecap="round"
			fill="none"
		/>
		<Path
			d="M590 498 V750"
			stroke={color}
			strokeWidth={33}
			strokeLinecap="round"
		/>
		<Path
			d="M600 492 C 646 512 686 480 706 400 L 712 378"
			stroke={color}
			strokeWidth={33}
			strokeLinecap="round"
			fill="none"
		/>
	</Svg>
);

/**
 * The empty state (docs/design/components.md § 20).
 *
 * **Empty is not an error.** No warning colour, no apology, no marketing line:
 * the headline says what the screen is for, and the second line names the ACTION
 * the reader can take. The second line is required by the type, not optional by
 * convention — an empty state with no second line is a dead end, and the type is
 * where that rule is enforced.
 */
export type EmptyStateProps = {
	headline: string;
	/** The action the reader can take. Required: see the note above. */
	next: string;
	action?: { label: string; onPress: () => void; testID?: string };
	testID?: string;
};

export const EmptyState = ({
	headline,
	next,
	action,
	testID,
}: EmptyStateProps) => {
	const markColor = useTokenColor("ink-dim");
	return (
		<View className={emptyStateClasses} testID={testID}>
			<BrandMark size={48} color={markColor} />
			<Text className="text-center text-body text-ink-muted">{headline}</Text>
			<Text className="text-center text-body-sm text-ink-dim">{next}</Text>
			{action ? (
				<Button
					label={action.label}
					onPress={action.onPress}
					testID={action.testID}
					variant="outline"
					size="md"
				/>
			) : null}
		</View>
	);
};
