import { describe, expect, it } from "vitest";

import type {
	ScheduleMonitorListing,
	ScheduleMonitorRow,
	ScheduleSupervisorInfo,
	SchedulesResponse,
	ScheduleWakeListing,
	ScheduleWakeRow,
} from "@/contracts";
import {
	dueLabel,
	familyState,
	formatWakeDuration,
	GONE_MONITORS_CLAUSE,
	GONE_WAKES_CLAUSE,
	type MonitorLineView,
	monitorAlerting,
	monitorEntryClause,
	monitorEntryViews,
	monitorSectionSummary,
	monitorSlot,
	monitorTail,
	NOTHING_ARMED_BODY,
	PARKED_MONITORS_CLAUSE,
	PARKED_WAKES_CLAUSE,
	readErrorClause,
	scheduleRefusalSentence,
	schedulesEmpty,
	showLessMonitorLabel,
	showLessWakeLabel,
	showMoreMonitorLabel,
	showMoreWakeLabel,
	supervisorFires,
	supervisorLead,
	truncatedClause,
	wakeCadenceWord,
	wakeDueWord,
	wakeEntryClause,
	wakeEntryViews,
	wakeLineView,
	wakeSectionSummary,
} from "@/features/schedules/schedules-copy";
import { RelayError } from "@/relay";

/* ------------------------------------------------------------------ values */

const NOW = 1_791_491_000_000;

const wakeRow = (
	overrides: Partial<ScheduleWakeRow> = {},
): ScheduleWakeRow => ({
	id: "w1",
	message: "check the shared inbox",
	next_due_at: NOW + 3_600_000,
	every_ms: null,
	until_at: null,
	limit: null,
	fired_count: 0,
	overdue_s: 0,
	stale: false,
	last_fired_at: null,
	last_attempt_at: null,
	...overrides,
});

const monitorRow = (
	overrides: Partial<ScheduleMonitorRow> = {},
): ScheduleMonitorRow => ({
	id: "m1",
	name: "Repo pull requests",
	tool: "bash",
	arguments: {},
	description: "watch the repo for new pull requests",
	every_ms: 300_000,
	until_at: null,
	notify: true,
	sort_lines: false,
	ignore: [],
	cwd: "~",
	created_at: NOW - 3_600_000,
	next_due_at: NOW + 240_000,
	last_check_at: NOW - 240_000,
	checks: 12,
	deliveries: 3,
	consecutive_failures: 0,
	disabled: false,
	disabled_reason: "",
	due_in_s: 240,
	last_check_age_s: 240,
	state: "armed",
	unavailable_since: 0,
	health: null,
	...overrides,
});

const wakeListing = (
	overrides: Partial<ScheduleWakeListing> = {},
): ScheduleWakeListing => ({
	entries: [],
	generated_at: NOW,
	total: 0,
	truncated: false,
	supervisor: { supported: true, running: true, detail: "" },
	read_error: false,
	...overrides,
});

const monitorListing = (
	overrides: Partial<ScheduleMonitorListing> = {},
): ScheduleMonitorListing => ({
	entries: [],
	generated_at: NOW,
	total: 0,
	truncated: false,
	read_error: false,
	...overrides,
});

const supervisor = (
	overrides: Partial<ScheduleSupervisorInfo> = {},
): ScheduleSupervisorInfo => ({
	supported: true,
	running: true,
	detail: "",
	...overrides,
});

/* -------------------------------------------------------------- durations */

describe("formatWakeDuration", () => {
	/* EVERY expectation here was generated by running the ORIGINAL —
	 * `local_operator/harness/wake.py::format_duration` — at the route's merge
	 * (`5e59e0cd06`), so this pins the port against the process, not against a
	 * second reading of the algorithm. */
	it.each([
		[60_000, "1m"],
		[3_600_000, "1h"],
		[5_400_000, "1h30m"],
		[86_400_000, "1d"],
		[604_800_000, "1w"],
		[45_000, "45s"],
		[1_500_000, "25m"],
		[90_000, "1m30s"],
		[172_800_000, "2d"],
		[691_200_000, "1w1d"],
		[660_000, "11m"],
		[1_000, "1s"],
		[90_000_000, "1d1h"],
	] as const)("%i ms reads %s", (ms, expected) => {
		expect(formatWakeDuration(ms)).toBe(expected);
	});
});

describe("dueLabel", () => {
	/* The same rule, on `cli._format_due`: thresholds generated from the CLI at
	 *  the same ref — including both sides of all three boundaries. */
	it.each([
		[45, "in 45s"],
		[89, "in 89s"],
		[90, "in 1m"],
		[299, "in 4m"],
		[300, "in 5m"],
		[5_399, "in 89m"],
		[5_400, "in 1h"],
		[5_401, "in 1h"],
		[172_799, "in 47h"],
		[172_800, "in 2d"],
		[0, "in 0s"],
		[-1, "1s overdue"],
		[-90, "1m overdue"],
		[-300, "5m overdue"],
		[-432_000, "5d overdue"],
	] as const)("%i s reads %s", (seconds, expected) => {
		expect(dueLabel(seconds)).toBe(expected);
	});
});

/* ------------------------------------------------------------- wake rows */

describe("wake row vocabulary", () => {
	it("spells the cadence the desktop spells, bounded budget included", () => {
		expect(wakeCadenceWord(null, null)).toBe("once");
		expect(wakeCadenceWord(86_400_000, null)).toBe("every 1d");
		expect(wakeCadenceWord(86_400_000, 3)).toBe("every 1d · 3 left");
		/* A spent budget is named as spent rather than as `0 left`, which would
		 *  promise a fire the schedule cannot make. */
		expect(wakeCadenceWord(86_400_000, 0)).toBe(
			"every 1d · no deliveries left",
		);
	});

	it("says `stale` instead of a clock the supervisor has given up on", () => {
		const stale = wakeRow({
			next_due_at: NOW - 8 * 86_400_000,
			stale: true,
		});
		expect(wakeDueWord(stale, NOW)).toBe("stale");
		expect(wakeDueWord(wakeRow(), NOW)).toBe("in 60m");
	});

	it("drops the due slot on a parked entry and on a spent budget", () => {
		const parked = wakeLineView(wakeRow(), NOW, true);
		expect(parked.due).toBe("");
		/* The cadence is what the work IS and stays true under a park. */
		expect(parked.cadence).toBe("once");

		const spent = wakeLineView(
			wakeRow({ limit: 2, fired_count: 2, every_ms: 60_000 }),
			NOW,
			false,
		);
		expect(spent.due).toBe("");
		expect(spent.cadence).toBe("every 1m · no deliveries left");
	});

	it("keeps a stale row's flag even where the slot carries it", () => {
		const row = wakeLineView(wakeRow({ stale: true }), NOW, false);
		expect(row.stale).toBe(true);
		expect(row.due).toBe("stale");
	});

	it("derives the remaining budget with the backend's own arithmetic", () => {
		/* `remaining` is not on this wire — the row carries `limit` and
		 *  `fired_count` — so the same `max(limit - fired_count, 0)` the harness
		 *  uses (`wake.py::due_while_down`) is the one derivation allowed here. */
		const row = wakeLineView(
			wakeRow({ limit: 5, fired_count: 4, every_ms: 3_600_000 }),
			NOW,
			false,
		);
		expect(row.cadence).toBe("every 1h · 1 left");
	});

	it("clamps a fired-beyond-limit row to the spent word, not a negative count", () => {
		const row = wakeLineView(
			wakeRow({ limit: 1, fired_count: 3, every_ms: 3_600_000 }),
			NOW,
			false,
		);
		expect(row.cadence).toBe("every 1h · no deliveries left");
	});
});

describe("wake entry heads", () => {
	const entry = (overrides = {}) => ({
		session_id: "aaaa11112222",
		name: "Invoices follow-up",
		cwd: "~/work/invoices",
		origin: "",
		updated_at: NOW - 90_000,
		dormant: false,
		ghost: false,
		next_due_at: NOW + 3_600_000,
		schedules: [wakeRow()],
		...overrides,
	});

	it("counts and dates an armed entry", () => {
		/* +3,600 s reads `in 60m`: the CLI's minute band runs to 90 minutes
		 *  (`_format_due`), and the port keeps the band, not a prettier hour. */
		expect(wakeEntryClause(entry(), NOW)).toBe("1 wake · next in 60m");
		expect(
			wakeEntryClause(
				entry({ schedules: [wakeRow(), wakeRow({ id: "w2" })] }),
				NOW,
			),
		).toBe("2 wakes · next in 60m");
	});

	it("replaces count and instant with the parked sentence", () => {
		expect(wakeEntryClause(entry({ dormant: true }), NOW)).toBe(
			PARKED_WAKES_CLAUSE,
		);
	});

	it("gives a ghost its own sentence, not the parked one", () => {
		/* The phone's deliberate split: the desktop collapses `dormant ||
		 *  ghost` into "Parked — wakes resume after its next turn", but a
		 *  conversation that no longer exists has no next turn — the
		 *  supervisor and the CLI treat ghost as the stronger, distinct fact. */
		expect(wakeEntryClause(entry({ ghost: true }), NOW)).toBe(
			GONE_WAKES_CLAUSE,
		);
		expect(GONE_WAKES_CLAUSE).not.toBe(PARKED_WAKES_CLAUSE);
	});

	it("falls back to the count when no instant is knowable", () => {
		expect(wakeEntryClause(entry({ next_due_at: null }), NOW)).toBe("1 wake");
	});
});

/* ----------------------------------------------------------- monitor rows */

describe("monitor row vocabulary", () => {
	it("passes the wire's state words through and dates only armed rows", () => {
		expect(monitorSlot(monitorRow({ state: "dormant" }))).toBe("dormant");
		expect(monitorSlot(monitorRow({ state: "disabled" }))).toBe("disabled");
		expect(monitorSlot(monitorRow({ state: "expired" }))).toBe("expired");
		/* An unknown word is its own word, never mapped onto a known one. */
		expect(monitorSlot(monitorRow({ state: "hibernating" }))).toBe(
			"hibernating",
		);
		expect(monitorSlot(monitorRow())).toBe("in 4m");
		expect(
			monitorSlot(monitorRow({ due_in_s: -300, next_due_at: NOW - 300_000 })),
		).toBe("5m overdue");
		expect(monitorSlot(monitorRow({ next_due_at: null, due_in_s: null }))).toBe(
			"waiting",
		);
	});

	it("suppresses the slot under a parked or gone entry", () => {
		expect(monitorLineViewFor(monitorRow()).slot).toBe("in 4m");
		/* `monitorLineView` is the suppression's home: the wire keeps sending a
		 *  due clock on a parked row, and the row must not print it. */
		expect(monitorLineViewFor(monitorRow(), true).slot).toBe("");
	});

	it("orders the health tail the way the band does", () => {
		/* An unavailable episode outranks a frozen failure count (the count
		 *  halted when the tool went out of reach). */
		expect(
			monitorTail(
				monitorRow({
					unavailable_since: NOW - 300_000,
					health: "tool unavailable since 16:25 — retrying",
					consecutive_failures: 3,
				}),
			),
		).toBe("tool unavailable since 16:25 — retrying");
		expect(monitorTail(monitorRow({ consecutive_failures: 2 }))).toBe(
			"2 failed",
		);
		expect(
			monitorTail(
				monitorRow({
					health:
						"9 checks, 0 deliveries — nothing has changed (confirm the call observes what you expect)",
				}),
			),
		).toBe(
			"9 checks, 0 deliveries — nothing has changed (confirm the call observes what you expect)",
		);
		expect(monitorTail(monitorRow())).toBeNull();
	});

	it("marks news without calling a parked row attention", () => {
		expect(monitorAlerting(monitorRow())).toBe(false);
		expect(monitorAlerting(monitorRow({ state: "disabled" }))).toBe(true);
		expect(monitorAlerting(monitorRow({ state: "expired" }))).toBe(true);
		expect(monitorAlerting(monitorRow({ unavailable_since: 1 }))).toBe(true);
		expect(monitorAlerting(monitorRow({ consecutive_failures: 1 }))).toBe(true);
		/* Dormant is the parked clause's business, not the attention count's. */
		expect(monitorAlerting(monitorRow({ state: "dormant" }))).toBe(false);
	});

	it("heads a monitor entry with its count, next check, or parked sentence", () => {
		const entry = {
			session_id: "bbbb33334444",
			name: "Portfolio rebalance",
			cwd: "~",
			origin: "",
			updated_at: NOW,
			dormant: false,
			ghost: false,
			next_due_at: NOW + 240_000,
			monitors: [monitorRow()],
		};
		expect(monitorEntryClause(entry, NOW)).toBe("1 monitor · next in 4m");
		expect(monitorEntryClause({ ...entry, dormant: true }, NOW)).toBe(
			PARKED_MONITORS_CLAUSE,
		);
		expect(monitorEntryClause({ ...entry, ghost: true }, NOW)).toBe(
			GONE_MONITORS_CLAUSE,
		);
	});
});

/* ------------------------------------------------------- the family states */

describe("the four family states stay four", () => {
	it("answers unreadable before anything else, even over an empty store", () => {
		/* `read_error` is terminal: the store could not be read, so entries
		 *  being empty is not evidence of anything. This is the assertion the
		 *  whole surface exists for. */
		expect(familyState(wakeListing({ read_error: true }))).toBe("unreadable");
		expect(familyState(monitorListing({ read_error: true }))).toBe(
			"unreadable",
		);
	});

	it("answers empty only for a readable store with nothing in it", () => {
		expect(familyState(wakeListing())).toBe("empty");
		expect(familyState(monitorListing())).toBe("empty");
		expect(
			familyState(
				wakeListing({
					entries: [
						{
							session_id: "aaaa11112222",
							name: "Invoices follow-up",
							cwd: "~",
							origin: "",
							updated_at: NOW,
							dormant: false,
							ghost: false,
							next_due_at: NOW + 3_600_000,
							schedules: [wakeRow()],
						},
					],
				}),
			),
		).toBe("ready");
	});

	it("never calls a payload empty while either family could not be read", () => {
		const both: SchedulesResponse = {
			wakes: wakeListing({ read_error: true }),
			monitors: monitorListing(),
		};
		expect(schedulesEmpty(both)).toBe(false);
		const other: SchedulesResponse = {
			wakes: wakeListing(),
			monitors: monitorListing({ read_error: true }),
		};
		expect(schedulesEmpty(other)).toBe(false);
	});

	it("calls the double-empty payload empty — and only that one", () => {
		expect(
			schedulesEmpty({ wakes: wakeListing(), monitors: monitorListing() }),
		).toBe(true);
		expect(
			schedulesEmpty({
				wakes: wakeListing(),
				monitors: monitorListing({
					entries: [
						{
							session_id: "bbbb33334444",
							name: "x",
							cwd: "",
							origin: "",
							updated_at: NOW,
							dormant: false,
							ghost: false,
							next_due_at: null,
							monitors: [monitorRow()],
						},
					],
				}),
			}),
		).toBe(false);
	});

	it("names the failed family in its sentence", () => {
		expect(readErrorClause("wakes")).toContain("wakes");
		expect(readErrorClause("monitors")).toContain("monitors");
		expect(readErrorClause("wakes")).not.toBe(readErrorClause("monitors"));
	});

	it("states the bounded slice rather than implying completeness", () => {
		expect(truncatedClause("wakes", 200, 205)).toBe(
			"Showing 200 of 205 conversations with wakes.",
		);
		expect(truncatedClause("monitors", 12, 30)).toBe(
			"Showing 12 of 30 conversations with monitors.",
		);
	});
});

/* ------------------------------------------------------------- supervisor */

describe("the supervisor sentences", () => {
	it("picks the platform reason before the unverifiable one", () => {
		/* `supported: false` also reports `verifiable: false`, so the order is
		 *  the whole rule: a Linux user must read the platform sentence. */
		expect(supervisorLead(supervisor({ supported: false }))).toContain(
			"not supervised on this platform yet",
		);
		expect(
			supervisorLead(supervisor({ supported: false, verifiable: false })),
		).toContain("not supervised on this platform yet");
	});

	it("does not claim somebody else's silence is a stopped supervisor", () => {
		const line = supervisorLead(supervisor({ verifiable: false }));
		expect(line).toContain("Nothing supervises the wakes below");
		expect(line).not.toContain("not running");
	});

	it("names the installed-but-stopped case, and says nothing when it is fine", () => {
		expect(supervisorLead(supervisor({ running: false }))).toContain(
			"installed but not running",
		);
		expect(supervisorLead(supervisor())).toBe("");
	});

	it("reads an absent verifiable as able to speak", () => {
		expect(
			supervisorFires({ supported: true, running: true, detail: "" }),
		).toBe(true);
		expect(
			supervisorFires({
				supported: true,
				running: true,
				detail: "",
				verifiable: false,
			}),
		).toBe(false);
		expect(
			supervisorFires({
				supported: true,
				running: false,
				detail: "",
				verifiable: true,
			}),
		).toBe(false);
	});
});

/* ----------------------------------------------------------- entry views */

describe("entry views", () => {
	it("caps a long conversation's rows and counts the hidden ones", () => {
		const listing = wakeListing({
			entries: [
				{
					session_id: "aaaa11112222",
					name: "Many wakes",
					cwd: "~",
					origin: "",
					updated_at: NOW,
					dormant: false,
					ghost: false,
					next_due_at: NOW + 60_000,
					schedules: [
						wakeRow({ id: "w1" }),
						wakeRow({ id: "w2" }),
						wakeRow({ id: "w3" }),
						wakeRow({ id: "w4" }),
					],
				},
			],
		});
		const [entry] = wakeEntryViews(listing, NOW);
		expect(entry?.rows).toHaveLength(4);
		expect(entry?.hidden).toBe(1);
	});

	it("suppresses every row's instant under a parked entry", () => {
		const listing = wakeListing({
			entries: [
				{
					session_id: "bbbb33334444",
					name: "Parked one",
					cwd: "~",
					origin: "",
					updated_at: NOW,
					dormant: true,
					ghost: false,
					next_due_at: NOW + 60_000,
					schedules: [wakeRow()],
				},
			],
		});
		const [entry] = wakeEntryViews(listing, NOW);
		expect(entry?.clause).toBe(PARKED_WAKES_CLAUSE);
		expect(entry?.rows[0]?.due).toBe("");
	});

	it("derives monitor views with the entry-level clamp too", () => {
		const listing = monitorListing({
			entries: [
				{
					session_id: "cccc55556666",
					name: "Many watches",
					cwd: "~",
					origin: "",
					updated_at: NOW,
					dormant: false,
					ghost: false,
					next_due_at: NOW + 60_000,
					monitors: [
						monitorRow({ id: "m1" }),
						monitorRow({ id: "m2" }),
						monitorRow({ id: "m3" }),
						monitorRow({ id: "m4" }),
						monitorRow({ id: "m5" }),
					],
				},
			],
		});
		const [entry] = monitorEntryViews(listing, NOW);
		expect(entry?.rows).toHaveLength(5);
		expect(entry?.hidden).toBe(2);
		expect(entry?.rows[0]?.slot).toBe("in 4m");
	});
});

/* ----------------------------------------------------------- section sums */

describe("section summaries", () => {
	it("counts wakes as scheduled rows", () => {
		expect(wakeSectionSummary([])).toBe("0 scheduled");
		expect(
			wakeSectionSummary([
				wakeLineView(wakeRow(), NOW, false),
				wakeLineView(wakeRow({ id: "w2" }), NOW, false),
			]),
		).toBe("2 scheduled");
	});

	it("calls out how many monitors need attention", () => {
		expect(monitorSectionSummary([])).toBe("0 armed");
		expect(
			monitorSectionSummary(
				[
					monitorEntryViews(
						monitorListing({
							entries: [
								{
									session_id: "a",
									name: "a",
									cwd: "",
									origin: "",
									updated_at: NOW,
									dormant: false,
									ghost: false,
									next_due_at: NOW,
									monitors: [monitorRow(), monitorRow({ id: "m2" })],
								},
							],
						}),
						NOW,
					)[0]?.rows ?? [],
				][0] ?? [],
			),
		).toBe("2 armed");
		expect(
			monitorSectionSummary([
				monitorLineViewFor(monitorRow({ state: "disabled" })),
				monitorLineViewFor(monitorRow({ id: "m2" })),
			]),
		).toBe("1 of 2 need attention");
	});
});

/* ---------------------------------------------------------------- labels */

describe("labels", () => {
	it("pluralises the disclosure both ways (the desktop shipped `1 more wakes`)", () => {
		expect(showMoreWakeLabel(1)).toBe("Show 1 more wake");
		expect(showMoreWakeLabel(3)).toBe("Show 3 more wakes");
		expect(showMoreMonitorLabel(1)).toBe("Show 1 more monitor");
		expect(showMoreMonitorLabel(3)).toBe("Show 3 more monitors");
		expect(showLessWakeLabel).toBe("Show fewer wakes");
		expect(showLessMonitorLabel).toBe("Show fewer monitors");
	});

	it("keeps the empty state's copy honest about what wakes and monitors do", () => {
		expect(NOTHING_ARMED_BODY).toContain("Wakes");
		expect(NOTHING_ARMED_BODY).toContain("monitors");
	});
});

describe("scheduleRefusalSentence", () => {
	it("carries the relay's own sentence for a definitive refusal", () => {
		expect(
			scheduleRefusalSentence(
				new RelayError("rejected", "unknown session", { status: 404 }),
			),
		).toBe("unknown session");
	});

	it("never lets a client-side diagnostic reach user copy", () => {
		expect(
			scheduleRefusalSentence(
				new RelayError(
					"malformed-frame",
					"GET /api/schedules did not match the relay contract",
				),
			),
		).toBeNull();
	});

	it("leaves connection failures to the connection's own surface", () => {
		expect(
			scheduleRefusalSentence(
				new RelayError("transport", "could not reach it"),
			),
		).toBeNull();
		expect(scheduleRefusalSentence(new Error("plain"))).toBeNull();
	});
});

/* ---------------------------------------------------------------- helpers */

/**
 * One monitor row's VIEW, through the entry-level derivation the surface
 * actually reads — suppression included. A helper rather than calling the
 * component, because these tests are about the state machine, and a renderer
 * would make them about React Native.
 */
function monitorLineViewFor(
	row: ScheduleMonitorRow,
	suppressed = false,
): MonitorLineView {
	const [entry] = monitorEntryViews(
		monitorListing({
			entries: [
				{
					session_id: "helper",
					name: "helper",
					cwd: "",
					origin: "",
					updated_at: NOW,
					dormant: suppressed,
					ghost: false,
					next_due_at: NOW,
					monitors: [row],
				},
			],
		}),
		NOW,
	);
	const view = entry?.rows[0];
	if (view === undefined)
		throw new Error("unreachable: the helper seeds one row");
	return view;
}
